Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg as Database
ModuleNotFoundError: No module named 'psycopg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 27, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tresjggi/cupidapp/passenger_wsgi.py", line 1, in <module>
    from btre.wsgi import application
  File "/home/tresjggi/cupidapp/btre/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tresjggi/cupidapp/listings/models.py", line 4, in <module>
    from realtors.models import Realtor
  File "/home/tresjggi/cupidapp/realtors/models.py", line 4, in <module>
    class Realtor(models.Model):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/base.py", line 143, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/options.py", line 243, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/utils.py", line 193, in create_connection
    backend = load_backend(db["ENGINE"])
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module
Traceback (most recent call last):
  File "/home/tresjggi/cupidapp/passenger_wsgi.py", line 1, in <module>
    from btre.wsgi import application
  File "/home/tresjggi/cupidapp/btre/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: listings_listing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/cupidapp/pages/views.py", line 18, in index
    return render(request, 'pages/index.html', context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/defaulttags.py", line 320, in render
    if match:
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 412, in __bool__
    self._fetch_all()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: listings_listing
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: listings_listing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/cupidapp/pages/views.py", line 18, in index
    return render(request, 'pages/index.html', context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/defaulttags.py", line 320, in render
    if match:
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 412, in __bool__
    self._fetch_all()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: listings_listing
Not Found: /contact
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: listings_listing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/cupidapp/pages/views.py", line 18, in index
    return render(request, 'pages/index.html', context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/template/defaulttags.py", line 320, in render
    if match:
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 412, in __bool__
    self._fetch_all()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: listings_listing
Traceback (most recent call last):
  File "/home/tresjggi/cupidapp/passenger_wsgi.py", line 1, in <module>
    from btre.wsgi import application
  File "/home/tresjggi/cupidapp/btre/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tresjggi/cupidapp/btre/settings.py", line 80
    'PORT' : '3306'
           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/tresjggi/cupidapp/passenger_wsgi.py", line 1, in <module>
    from btre.wsgi import application
  File "/home/tresjggi/cupidapp/btre/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tresjggi/cupidapp/btre/settings.py", line 80
    'PORT' : '3306'
           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/tresjggi/cupidapp/passenger_wsgi.py", line 1, in <module>
    from btre.wsgi import application
  File "/home/tresjggi/cupidapp/btre/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tresjggi/cupidapp/btre/settings.py", line 80
    'PORT' : '3306'
           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/tresjggi/cupidapp/passenger_wsgi.py", line 1, in <module>
    from btre.wsgi import application
  File "/home/tresjggi/cupidapp/btre/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tresjggi/cupidapp/btre/settings.py", line 80
    'PORT' : '3306'
           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/tresjggi/cupidapp/passenger_wsgi.py", line 1, in <module>
    from btre.wsgi import application
  File "/home/tresjggi/cupidapp/btre/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tresjggi/cupidapp/btre/settings.py", line 80
    'PORT' : '3306'
           ^
SyntaxError: invalid syntax
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /static/js/bootstrap.bundle.min.js.map
Not Found: /static/js/lightbox.min.map
Not Found: /robots.txt
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /static/js/bootstrap.bundle.min.js.map
Not Found: /static/js/lightbox.min.map
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /static/js/bootstrap.bundle.min.js.map
Not Found: /static/js/lightbox.min.map
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /static/js/bootstrap.bundle.min.js.map
Not Found: /static/js/lightbox.min.map
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: //wp-includes/wlwmanifest.xml
Not Found: //xmlrpc.php
Not Found: //blog/wp-includes/wlwmanifest.xml
Not Found: //web/wp-includes/wlwmanifest.xml
Not Found: //wordpress/wp-includes/wlwmanifest.xml
Not Found: //website/wp-includes/wlwmanifest.xml
Not Found: //wp/wp-includes/wlwmanifest.xml
Not Found: //news/wp-includes/wlwmanifest.xml
Not Found: //2018/wp-includes/wlwmanifest.xml
Not Found: //2019/wp-includes/wlwmanifest.xml
Not Found: //shop/wp-includes/wlwmanifest.xml
Not Found: //wp1/wp-includes/wlwmanifest.xml
Not Found: //test/wp-includes/wlwmanifest.xml
Not Found: //media/wp-includes/wlwmanifest.xml
Not Found: //wp2/wp-includes/wlwmanifest.xml
Not Found: //site/wp-includes/wlwmanifest.xml
Not Found: //cms/wp-includes/wlwmanifest.xml
Not Found: //sito/wp-includes/wlwmanifest.xml
Not Found: /.env
Not Found: /.remote
Not Found: /.local
Not Found: /.production
Not Found: /vendor/.env
Not Found: /lib/.env
Not Found: /lab/.env
Not Found: /cronlab/.env
Not Found: /cron/.env
Not Found: /core/.env
Not Found: /core/app/.env
Not Found: /core/Datavase/.env
Not Found: /database/.env
Not Found: /config/.env
Not Found: /assets/.env
Not Found: /app/.env
Not Found: /apps/.env
Not Found: /uploads/.env
Not Found: /sitemaps/.env
Not Found: /saas/.env
Not Found: /api/.env
Not Found: /psnlink/.env
Not Found: /exapi/.env
Not Found: /site/.env
Not Found: /web/.env
Not Found: /public/.env
Not Found: /en/.env
Not Found: /tools/.env
Not Found: /v1/.env
Not Found: /v2/.env
Not Found: /administrator/.env
Not Found: /laravel/.env
Not Found: /robots.txt
Not Found: /robots.txt
Not Found: /index.php
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /static/images/loading.gif
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /static/images/loading.gif
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /static/images/loading.gif
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /static/images/loading.gif
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /media/photo/2023/06/22/important.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /static/images/loading.gif
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /media/photo/2023/06/22/important.jpg
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Not Found: /media/photo/2023/06/22/important.jpg
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /media/photo/2023/06/22/important.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Not Found: /static/images/loading.gif
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /media/photos/2023/06/22/home-1.jpg
Not Found: /static/images/loading.gif
Not Found: /adim
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /media/photo/2023/06/22/important.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /static/images/loading.gif
Forbidden (CSRF token from POST incorrect.): /admin/login/
Not Found: /static/images/loading.gif
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
    return qs.filter(user=request.user)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
    return qs.filter(user=request.user)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
    return qs.filter(user=request.user)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
    return qs.filter(realtor=request.realtor)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
    return qs.filter(realtor=request.realtor)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
    return qs.filter(realtor=request.realtor)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
    return qs.filter(realtor=request.realtor)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
    return qs.filter(realtor=request.realtor)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
    return qs.filter(realtor=request.realtor)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /media/photos/2023/06/22/home-inside-1.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_1QQa0rC.jpg
Not Found: /media/photos/2023/06/22/home-inside-5.jpg
Not Found: /media/photos/2023/06/22/home-inside-4.jpg
Not Found: /media/photos/2023/06/22/home-inside-4_nMPmWyk.jpg
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /static/images/loading.gif
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Internal Server Error: /admin/listings/listing/
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/home/tresjggi/cupidapp/listings/admin.py", line 17, in get_queryset
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: address, bathrooms, bedroom, city, description, garage, id, is_published, list_date, lot_size, photo_1, photo_2, photo_3, photo_4, photo_5, photo_6, photo_main, price, realtor, realtor_id, sqft, state, title, zipcode
Not Found: /favicon.ico
Invalid HTTP_HOST header: 'mail.mosupply.nl'. You may need to add 'mail.mosupply.nl' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mail.mosupply.nl'. You may need to add 'mail.mosupply.nl' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'mail.mosupply.nl'. You may need to add 'mail.mosupply.nl' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/tresjggi/virtualenv/cupidapp/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mail.mosupply.nl'. You may need to add 'mail.mosupply.nl' to ALLOWED_HOSTS.
Bad Request: /
Bad Request: /
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /robots.txt
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
Not Found: /favicon.ico
Not Found: /static/images/loading.gif
